<?xml version="1.0" standalone="yes"?>
<!-- logreq request file -->
<!-- logreq version 1.0 / dtd version 1.0 -->
<!-- Do not edit this file! -->
<!DOCTYPE requests [
  <!ELEMENT requests (internal | external)*>
  <!ELEMENT internal (generic, (provides | requires)*)>
  <!ELEMENT external (generic, cmdline?, input?, output?, (provides | requires)*)>
  <!ELEMENT cmdline (binary, (option | infile | outfile)*)>
  <!ELEMENT input (file)+>
  <!ELEMENT output (file)+>
  <!ELEMENT provides (file)+>
  <!ELEMENT requires (file)+>
  <!ELEMENT generic (#PCDATA)>
  <!ELEMENT binary (#PCDATA)>
  <!ELEMENT option (#PCDATA)>
  <!ELEMENT infile (#PCDATA)>
  <!ELEMENT outfile (#PCDATA)>
  <!ELEMENT file (#PCDATA)>
  <!ATTLIST requests
    version CDATA #REQUIRED
  >
  <!ATTLIST internal
    package CDATA #REQUIRED
    priority (9) #REQUIRED
    active (0 | 1) #REQUIRED
  >
  <!ATTLIST external
    package CDATA #REQUIRED
    priority (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8) #REQUIRED
    active (0 | 1) #REQUIRED
  >
  <!ATTLIST provides
    type (static | dynamic | editable) #REQUIRED
  >
  <!ATTLIST requires
    type (static | dynamic | editable) #REQUIRED
  >
  <!ATTLIST file
    type CDATA #IMPLIED
  >
]>
<requests version="1.0">
  <internal package="biblatex" priority="9" active="1">
    <generic>latex</generic>
    <provides type="dynamic">
      <file>man.bcf</file>
    </provides>
    <requires type="dynamic">
      <file>man.bbl</file>
    </requires>
    <requires type="static">
      <file>blx-dm.def</file>
      <file>blx-compat.def</file>
      <file>biblatex.def</file>
      <file>standard.bbx</file>
      <file>abnt.bbx</file>
      <file>authoryear-comp.cbx</file>
      <file>abnt.cbx</file>
      <file>biblatex.cfg</file>
      <file>brazilian.lbx</file>
      <file>brazil.lbx</file>
      <file>brazilian-abnt.lbx</file>
      <file>brazil-abnt.lbx</file>
    </requires>
  </internal>
  <external package="biblatex" priority="5" active="1">
    <generic>biber</generic>
    <cmdline>
      <binary>biber</binary>
      <infile>man</infile>
    </cmdline>
    <input>
      <file>man.bcf</file>
    </input>
    <output>
      <file>man.bbl</file>
    </output>
    <provides type="dynamic">
      <file>man.bbl</file>
    </provides>
    <requires type="dynamic">
      <file>man.bcf</file>
    </requires>
  </external>
</requests>
